# Generated by Django 2.2 on 2022-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20220228_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
