# Generated by Django 2.2 on 2022-02-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20220228_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
