# Generated by Django 2.2 on 2022-02-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20220228_1308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('name', 'website')},
        ),
    ]
