# Generated by Django 2.2 on 2022-02-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20220228_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('superadmin', 1), ('owner', 2), ('seller', 3), ('distributor', 4), ('client', 5)], default=1),
        ),
    ]
