# Generated by Django 2.2 on 2022-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_city_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'superadmin'), (2, 'owner'), (3, 'seller'), (4, 'distributor'), (5, 'client')], default=1),
        ),
    ]
