# Generated by Django 2.2 on 2022-04-11 13:00

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.book_file_directory_path, validators=[utils.validators.validate_file_size, utils.validators.validate_file_extension]),
        ),
    ]
