# Generated by Django 2.2 on 2022-02-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220221_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
    ]
